--- 
- hosts: 172.31.36.54
  become: yes 
  tasks: 
  - name: install webservers
    apt:
     name: apache2
     state: present
  - name: install tree 
    apt: 
     name: tree 
     state: present




